### ISSUE TITLE
Support other chat platforms for control (notably, zulip)

### ISSUE THREAD

**Issue by lakinwecker** [lichess-org/pgn-mule#11]
With zulip's support for topics, we could make the output _much_ easier to organize as well.

**Comment by ornicar** [comment]
most of this repository is about the chat platform. It's, mostly, a chat bot.

I don't think supporting multiple platforms is desirable, instead I'll make a new version that only supports zulip.

Zulip very much encourages bots to be written in python, it's the only official option. For that reason I'm considering rewriting this to python.

https://zulip.com/api/writing-bots
